---
title: "Structure du prix des produits dans les différents marchés en Côte d'Ivoire"
author: "Amed BAH ~ Frederic AKADJE"
documentclass: report
format: pdf
toc: true
toc-expand: true
toccolor: blue
margin-left: 2.5cm
editor: visual
lang: fr
fontsize: 12pt
bibliography: references.bib
---

# Description

Dans le contexte économique actuel, marqué par une inflation constante et une incertitude croissante, la question de la variabilité des prix des produits et leur l'accessibilité dans les différents marchés est devenue cruciale. Les ménages sont contraints de jongler entre le désir de maintenir un certain niveau de vie et la nécessité de s'adapter à une réalité économique de plus en plus difficile. En Côte d'Ivoire, l'Etat s'engage résolument dans la lutte contre la vie chère, à travers certains organismes tels que le CNLVC (Conseil National de Lutte Contre la Vie Chère) et le OCPV (Office d'aide à la Commercialisation des Produits Vivriers). Ses actions visent à atténuer l'impact de l'inflation sur les populations vulnérables et à garantir l'accessibilité des produits de base à tous. Somme toute, ces initiatives sont précieuses pour assurer la stabilité économique et sociale en Côte d'Ivoire.

Cette étude vise à analyser la structure des prix sur les différents marchés ivoiriens.

Deux problématiques principales articuleront notre analyse: **comment les prix varie-t-ils** et **et qu'en est-il de leur accessibilité au sein des différents marchés en Côte d'Ivoire**.

En fin de compte, cette analyse approfondie vise à fournir des informations précieuses qui pourraient aider à élaborer des politiques efficaces pour atténuer l'impact de l'inflation sur les populations vulnérables en Côte d'Ivoire.

## Mise en oeuvre

### Collaboration et contribution

Le projet est disponible sur les repo github: \@ ou \@ . Aussi la mise place de ce projet a occasionné la conception d'une maqette pour l'application Shiny avant sa réalisation (maquette disponible sur : [ici](https://www.figma.com/file/IkEu8xdFRqfcr2R0eESQFC/Structure_Prix-team-library?type=design&mode=design&t=u1JtKOkRZorjGNiW-1)).

### Source de données

Ce projet a nécessité l'utilisation des sources de données suivantes:

-   Prix des produits dans les différents marchés en Côte d'Ivoire depuis Janvier 2022 (csv), OpendataCi : <https://data.gouv.ci/datasets/echo-du-marche>

-   Mise à jour des prix de gros et de détail sur certains marchés de la Côte d'Ivoire en 2016 (csv), OpendataCi : <https://data.gouv.ci/datasets/mise-a-jour-des-prix-de-gros-et-au-details-sur-certains-marches-en-2016>

-   Prix actuel des produits de marché (donnée scrappée), SIKA finance : <https://www.sikafinance.com/conso/liste_des_prix>

-   Catégorisation des produits du marché (pdf), OCPV : <https://www.ocpv-ci.com/doc/SYNTHESE/2023/SYNTHESE_PRIX_MOYENS_S13_2023.pdf>

-   Estimation du panier moyen (csv) : voir dossier /data/name.csv

# Data Processing

L'ensemble des tâches effectuées passe par un travail de fond sur les différentes données collectées. Ces tâches s'étendent depuis la collecte jusqu'au aux calculs des indicateurs.

## Collecte des données

## Transformation et nettoyage

## Gestion des valeurs manquantes

## Calcul des indicateurs

# REFERENCE

[@stringdist]
